#!/bin/bash
grunt exportAnalyticQueries -v
grunt exportAnalyticExports -v
grunt exportAuditLogs -v
grunt exportDevs -v
grunt exportProducts -v
grunt exportApps -v
grunt exportProxies -v
grunt exportProxyKVM -v
grunt exportEnvKVM -v
grunt exportOrgKVM -v
grunt exportFlowHooks -v
grunt exportAllSpecs -v
grunt exportTargetServers -v
grunt exportReports -v
grunt exportSharedFlows -v
grunt exportKeyStores -v
grunt exportVirtualHosts -v
grunt exportReferences -v
grunt exportCaches -v
grunt exportRoles -v
grunt exportCollections -v
grunt exportAlerts -v
grunt exportExtensions -v
grunt exportEnvResources -v
grunt exportOrgResources -v