openapi: 3.0.1
info:
  title: Search
  description: 'This API provides capabilities to perform global search across all entities in API Cloud'
  termsOfService: https://www.infosys.com/terms-of-use.html
  contact:
    name: API Cloud
    email: apicloud@infosys.com
  version: 1.0.0
servers:
- url: http://apicloud-staging.ad.infosys.com:31846/apiCloud/v1
- url: https://oneclickapi-gw.imapnext.com/apiCloud/v1
- url: https://apicloud-gw.infosysapps.com/apiCloud/v1
paths:
  /search:
    get:
      summary: Fetch a list of matching entities 
      description: Retrieve a list of entities with matching name or description 
      operationId: searchEntities
      parameters:
      - name: searchText
        in: query
        description: Text entered by user for global search
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: searchObject
        in: query
        description: Specific objects to be searched
        required: false
        style: form
        explode: true
        schema:
          type: string
          enum: 
          - "api"
          - "product"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Search'
        400:
          description: Bad Request
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        401:
          description: Unauthorized
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
      - api_key: []
components:
  schemas:
    Search:
      type: object
      properties:
        products:
            type: array
            items:
              $ref: '#/components/schemas/Product'
        apis:
            type: array
            items:
              $ref: '#/components/schemas/API'
    Product:
      type: object
      properties:
        productId:
          type: integer
          format: int32
        productName:
          type: string
        productDescription:
          type: string
        logo:
          type: string
        status: 
          type: boolean
        sequenceNumber:
          type: integer
          format: int32
        extension:
          $ref: '#/components/schemas/ProductExtension'
    ProductExtension:
      type: object
      properties:
        apiCount: 
          type: integer
          format: int32
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
    API:
      type: object
      properties:
        apiId:
          type: integer
          format: int32
        apiName:
          type: string
        apiVersion:
          type: string
        apiDescription:
          type: string
        apiAdditionalInfo:
          type: string
        productId:
          type: integer
          format: int32
        productName:
          type: string
        requestedBy: 
          type: string
        requestedTimestamp:
          type: string
        status: 
          type: boolean
        trending:
          type: boolean
        sequenceNumber:
          type: integer
          format: int32
        specPath: 
          type: string
        nbSecurity:
          type: string
        nbSecurityType:
          type: string
        nbCORS:
          type: boolean
        nbCSRF:
          type: boolean
        nbXSS:
          type: boolean
        sbSecurity:
          type: string
        sbSecurityType:
          type: string
        sbSSL:
          type: boolean
        sbTarget:
          type: string
        sbTargetType:
          type: string
        extension:
          $ref: '#/components/schemas/APIExtension'
        tags:
          type: array
          items: 
            type: string
    APIExtension:
      type: object
      properties:
        avgRating: 
          type: number
          format: double
        ratingCount:
          type: integer
          format: int32
        feedbackCount:
          type: integer
          format: int32
        adoptionCount:
          type: integer
          format: int32
  securitySchemes:
    api_key:
      type: apiKey
      name: X-Authorization
      in: header
