openapi: 3.0.1
info:
  title: FHIR PROVIDER DIRECTORY API
  version: "1.0"
  description: Test Description
servers:
- url: "https://amer-api-partner38-dev.apigee.net/infosys_health_portal_devportal_all-api"
#- url: //imapnext.com:5556/ihp/drug/formulary-ig/v1
tags:
- name: practitioner-role-controller
  description: Practitioner Role Controller
- name: practitioner-controller
  description: Practitioner Controller
paths:
  /fhir/Practitioner:
    get:
      tags:
      - practitioner-controller
      summary: findAllPractioner
      operationId: findAllPractionerUsingGET_1
      parameters:
      - name: "apikey"
        in: "header"
        description: "apikey"
        required: true
        schema:
          type: "string"
      - name: "jwt-token"
        in: "header"
        description: "jwt-token"
        required: true
        schema:
          type: "string"    
      - name: _id
        in: query
        description: _id
        schema:
          type: string
      - name: _language
        in: query
        description: _language
        schema:
          type: string
      - name: given
        in: query
        description: given
        schema:
          type: string
      - name: identifier
        in: query
        description: identifier
        schema:
          type: string
      - name: address
        in: query
        description: address
        schema:
          type: string
      - name: address-state
        in: query
        description: address-state
        schema:
          type: string
      - name: gender
        in: query
        description: gender
        schema:
          type: string
      - name: active
        in: query
        description: active
        schema:
          type: string
      - name: address-city
        in: query
        description: address-city
        schema:
          type: string
      - name: address-postalCode
        in: query
        description: address-postalCode
        schema:
          type: string
      - name: phonetic
        in: query
        description: phonetic
        schema:
          type: string
      - name: phone
        in: query
        description: phone
        schema:
          type: string
      - name: address-country
        in: query
        description: address-country
        schema:
          type: string
      - name: address-use
        in: query
        description: address-use
        schema:
          type: string
      - name: name
        in: query
        description: name
        schema:
          type: string
      - name: telecom
        in: query
        description: telecom
        schema:
          type: string
      - name: communication
        in: query
        description: communication
        schema:
          type: string
      - name: family
        in: query
        description: family
        schema:
          type: string
      - name: email
        in: query
        description: email
        schema:
          type: string
      - name: _format
        in: query
        description: _format
        schema:
          type: string
          default: json
      - name: _pretty
        in: query
        description: _pretty
        schema:
          type: boolean
          default: true
      responses:
        200:
          description: OK
          content:
            application/xml:
              schema:
                type: object
            application/json:
              schema:
                type: object
        401:
          description: Unauthorized
          content: {}
        403:
          description: Forbidden
          content: {}
        404:
          description: Not Found
          content: {}
  /fhir/PractitionerRole:
    get:
      tags:
      - practitioner-role-controller
      summary: findAllPractionerRole
      operationId: findAllPractionerRoleUsingGET_1
      parameters:
      - name: "apikey"
        in: "header"
        description: "apikey"
        required: true
        schema:
          type: "string"
      - name: "jwt-token"
        in: "header"
        description: "jwt-token"
        required: true
        schema:
          type: "string"    
      - name: _id
        in: query
        description: _id
        schema:
          type: string
      - name: _language
        in: query
        description: _language
        schema:
          type: string
      - name: date
        in: query
        description: date
        schema:
          type: string
      - name: identifier
        in: query
        description: identifier
        schema:
          type: string
      - name: specialty
        in: query
        description: specialty
        schema:
          type: string
      - name: role
        in: query
        description: role
        schema:
          type: string
      - name: practitioner
        in: query
        description: practitioner
        schema:
          type: string
      - name: active
        in: query
        description: active
        schema:
          type: string
      - name: endpoint
        in: query
        description: endpoint
        schema:
          type: string
      - name: service
        in: query
        description: service
        schema:
          type: string
      - name: phone
        in: query
        description: phone
        schema:
          type: string
      - name: organization
        in: query
        description: organization
        schema:
          type: string
      - name: location
        in: query
        description: location
        schema:
          type: string
      - name: telecom
        in: query
        description: telecom
        schema:
          type: string
      - name: email
        in: query
        description: email
        schema:
          type: string
      - name: _format
        in: query
        description: _format
        schema:
          type: string
          default: json
      - name: _pretty
        in: query
        description: _pretty
        schema:
          type: boolean
          default: true
      responses:
        200:
          description: OK
          content:
            application/xml:
              schema:
                type: object
            application/json:
              schema:
                type: object
        401:
          description: Unauthorized
          content: {}
        403:
          description: Forbidden
          content: {}
        404:
          description: Not Found
          content: {}
